# Generated by Django 6.0.4 on 2026-05-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_chofer_conectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='coordenadas',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Coordenadas de la ruta'),
        ),
    ]
